// <auto-generated />
namespace Coursemanger.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Course2019112717081 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Course2019112717081));
        
        string IMigrationMetadata.Id
        {
            get { return "201912040825206_Course2019112717081"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
